### PR TITLE
TAT queries testing

### PR DESCRIPTION
**Pull request by rklocke**
- Refactored functions for testing
- Added tests 
- Changed to plot the days between first MultiQC job and reports released instead of the last MultiQC job to prevent negative time from processing end to release
- Instead it now just flags below runs where the last MultiQC job is after the reports were released for 'All samples released' runs

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/themis/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/2)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @rklocke)

___
*[`TAT_audit/tests/test_TAT_queries.py` line 29 at r1](https://reviewable.io/reviews/eastgenomics/themis/2#-NEkb_ZED8byXYYaqhzt:-NEkb_ZED8byXYYaqhzu:b5v3k9n) ([raw file](https://github.com/eastgenomics/themis/blob/ba35d032a6fb0cc547bab9fd469f8c79f7b47abd/TAT_audit/tests/test_TAT_queries.py#L29)):*
> ```Python
>         "Distance incorrect when one change, same length"
>     )
>     assert tatq.get_distance(ticket_name2, run_name2) == 8, (
> ```

some options you have to do this so all tests are run:

- make a class with test functions inside, can handle lots of complexity and reusing test set up amongst lots of tests e.g.
```
class TestGetDistance():
    ticket_name = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name = '220901_A01303_0093_BHGNN5DRX2_TSO500'

    ticket_name2 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name2 = '220901_0094_BHGNN5DRX2_TSO500'

    ticket_name3 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name3 = '2209001_A01303_0094_2_BHGNNSDRX2_TSO500'

   def test_distance_2(self):
       assert tatq.get_distance(self.ticket_name, self.run_name) == 2, (
        "Distance incorrect when one change, same length"
        )

    def test_distance_8(self):
        ....    
```

- gather errors and assert in one, good for simple examples like this where you're just testing with different inputs:
```
def test_get_distance():
    ticket_name = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name = '220901_A01303_0093_BHGNN5DRX2_TSO500'

    ticket_name2 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name2 = '220901_0094_BHGNN5DRX2_TSO500'

    ticket_name3 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name3 = '2209001_A01303_0094_2_BHGNNSDRX2_TSO500'

    errors = []

    if not tatq.get_distance(ticket_name, run_name) == 2:
        errors.append("Failed to get correct distance of 2)

    if not tatq.get_distance(ticket_name2, run_name2) == 8:
        errors.append("Failed to get correct distance of 8)

    assert not errors, f'Error(s) found calculating distances: {"\n".join(errors)}'
```

- get your outputs up front and map to expected results:
```
def test_get_distance():
    ticket_name = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name = '220901_A01303_0093_BHGNN5DRX2_TSO500'

    ticket_name2 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name2 = '220901_0094_BHGNN5DRX2_TSO500'

    ticket1_output = tatq.get_distance(ticket_name, run_name)
    ticket2_output = tatq.get_distance(ticket_name2, run_name2)

    assert map((ticket1_output, ticket2_output), (2, 8)), "Failed to correctly calculate distances"
```

There's also `sub_tests` built into unit test you can use which will also work with pytest: https://docs.python.org/3/library/unittest.html#subtests



_Suggestion:_
```Python
def test_get_distance():
    ticket_name = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name = '220901_A01303_0093_BHGNN5DRX2_TSO500'

    ticket_name2 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name2 = '220901_0094_BHGNN5DRX2_TSO500'

    ticket_name3 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name3 = '2209001_A01303_0094_2_BHGNNSDRX2_TSO500'

    assert tatq.get_distance(ticket_name, run_name) == 2, (
        "Distance incorrect when one change, same length"
    )
    assert tatq.get_distance(ticket_name2, run_name2) == 8, (
        "Distance incorrect when characters are removed"
    )
    assert tatq.get_distance(ticket_name3, run_name3) == 3, (
        "Distance incorrect when characters are added"
    )   
```
___
*[`TAT_audit/utils/TAT_queries.py` line 1459 at r1](https://reviewable.io/reviews/eastgenomics/themis/2#-NEkfIfJ0sGPsiCEwHXM:-NEkfIfJ0sGPsiCEwHXN:b-k93zmo) ([raw file](https://github.com/eastgenomics/themis/blob/ba35d032a6fb0cc547bab9fd469f8c79f7b47abd/TAT_audit/utils/TAT_queries.py#L1459)):*
> ```Python
>     with open(filename, mode="w", encoding="utf-8") as message:
>         message.write(content)
>     beepy.beep(sound="ping")
> ```

adding the important features I see



_Code quote:_
```Python
beepy.beep(sound="ping")
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/2)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`TAT_audit/tests/test_TAT_queries.py` line 29 at r1](https://reviewable.io/reviews/eastgenomics/themis/2#-NEkb_ZED8byXYYaqhzt:-NFsX3P-E5ti9yPwczxK:b-hhps6h) ([raw file](https://github.com/eastgenomics/themis/blob/ba35d032a6fb0cc547bab9fd469f8c79f7b47abd/TAT_audit/tests/test_TAT_queries.py#L29)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

some options you have to do this so all tests are run:

- make a class with test functions inside, can handle lots of complexity and reusing test set up amongst lots of tests e.g.
```
class TestGetDistance():
    ticket_name = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name = '220901_A01303_0093_BHGNN5DRX2_TSO500'

    ticket_name2 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name2 = '220901_0094_BHGNN5DRX2_TSO500'

    ticket_name3 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name3 = '2209001_A01303_0094_2_BHGNNSDRX2_TSO500'

   def test_distance_2(self):
       assert tatq.get_distance(self.ticket_name, self.run_name) == 2, (
        "Distance incorrect when one change, same length"
        )

    def test_distance_8(self):
        ....    
```

- gather errors and assert in one, good for simple examples like this where you're just testing with different inputs:
```
def test_get_distance():
    ticket_name = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name = '220901_A01303_0093_BHGNN5DRX2_TSO500'

    ticket_name2 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name2 = '220901_0094_BHGNN5DRX2_TSO500'

    ticket_name3 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name3 = '2209001_A01303_0094_2_BHGNNSDRX2_TSO500'

    errors = []

    if not tatq.get_distance(ticket_name, run_name) == 2:
        errors.append("Failed to get correct distance of 2)

    if not tatq.get_distance(ticket_name2, run_name2) == 8:
        errors.append("Failed to get correct distance of 8)

    assert not errors, f'Error(s) found calculating distances: {"\n".join(errors)}'
```

- get your outputs up front and map to expected results:
```
def test_get_distance():
    ticket_name = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name = '220901_A01303_0093_BHGNN5DRX2_TSO500'

    ticket_name2 = '220901_A01303_0094_BHGNNSDRX2_TSO500'
    run_name2 = '220901_0094_BHGNN5DRX2_TSO500'

    ticket1_output = tatq.get_distance(ticket_name, run_name)
    ticket2_output = tatq.get_distance(ticket_name2, run_name2)

    assert map((ticket1_output, ticket2_output), (2, 8)), "Failed to correctly calculate distances"
```

There's also `sub_tests` built into unit test you can use which will also work with pytest: https://docs.python.org/3/library/unittest.html#subtests

</blockquote></details>

went with first option :)
___
*[`TAT_audit/utils/TAT_queries.py` line 1459 at r1](https://reviewable.io/reviews/eastgenomics/themis/2#-NEkfIfJ0sGPsiCEwHXM:-NFsXQsNEBGZZcnurf8P:b78eupw) ([raw file](https://github.com/eastgenomics/themis/blob/ba35d032a6fb0cc547bab9fd469f8c79f7b47abd/TAT_audit/utils/TAT_queries.py#L1459)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

adding the important features I see
</blockquote></details>

beepy has changed my life

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/2)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`TAT_audit/utils/TAT_queries.py` line 36 at r2](https://reviewable.io/reviews/eastgenomics/themis/2#-NFt7R7X0-SuBA9GfS06:-NFt7R7YDq7iStUcUXGF:b-29p8fs) ([raw file](https://github.com/eastgenomics/themis/blob/e1e4fbc865a5946cab348aece49150a8876f27a7/TAT_audit/utils/TAT_queries.py#L36)):*
> ```Python
> NO_OF_AUDIT_WEEKS = args.no_of_audit_weeks
> 
> ROOT_DIR = os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
> ```

is this to get the parent directory of the running script? if so using pathlib might be a bit easier, I tend to find it simpler than chaining `os.path` functions:

```
jethro@jethro-T490:~/Projects/tso500_combined_tsv_vs_vcf_check$ cat test.py 
from pathlib import Path

print(Path(__file__).absolute().parent)
print(Path(__file__).absolute().parents[0])
print(Path(__file__).absolute().parents[1])
print(Path(__file__).absolute().parents[2])
jethro@jethro-T490:~/Projects/tso500_combined_tsv_vs_vcf_check$ python3 test.py 
/home/jethro/Projects/tso500_combined_tsv_vs_vcf_check
/home/jethro/Projects/tso500_combined_tsv_vs_vcf_check
/home/jethro/Projects
/home/jethro
```



_Code quote:_
```Python
os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/2)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`TAT_audit/utils/TAT_queries.py` line 36 at r2](https://reviewable.io/reviews/eastgenomics/themis/2#-NFt7R7X0-SuBA9GfS06:-NFxJczS4CWblbP_JtFr:b6a4t5d) ([raw file](https://github.com/eastgenomics/themis/blob/e1e4fbc865a5946cab348aece49150a8876f27a7/TAT_audit/utils/TAT_queries.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this to get the parent directory of the running script? if so using pathlib might be a bit easier, I tend to find it simpler than chaining `os.path` functions:

```
jethro@jethro-T490:~/Projects/tso500_combined_tsv_vs_vcf_check$ cat test.py 
from pathlib import Path

print(Path(__file__).absolute().parent)
print(Path(__file__).absolute().parents[0])
print(Path(__file__).absolute().parents[1])
print(Path(__file__).absolute().parents[2])
jethro@jethro-T490:~/Projects/tso500_combined_tsv_vs_vcf_check$ python3 test.py 
/home/jethro/Projects/tso500_combined_tsv_vs_vcf_check
/home/jethro/Projects/tso500_combined_tsv_vs_vcf_check
/home/jethro/Projects
/home/jethro
```
</blockquote></details>

was to get the parent yes to find templates / the credentials.json, have updated os to Pathlib :)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
