### PR TITLE
Update first job timestamp for CEN, MYE and TWE runs

### PR DESCRIPTION
**Pull request by rklocke**
- The first job for all runs was taken as earliest job run in the 002 project, but for CEN, MYE and TWE runs it has been updated so it is the demultiplexing job in the staging area instead.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`TAT_audit/utils/TAT_queries.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/themis/10#-NIIBfoO3E1YIVEWOPEf:-NIIBfoO3E1YIVEWOPEg:b-tk7ywv) ([raw file](https://github.com/eastgenomics/themis/blob/3165f45d427dcde6c36432c49155469e4345a2a5/TAT_audit/utils/TAT_queries.py#L574)):*
> ```Python
>     def find_staging_demultiplex_jobs(self):
>         """
>         Find jobs in staging area (always demultiplexing)
> ```

other things do get run there / will be (i.e. eggd_conductor), demultiplexing apps will be eggd_bcl2fastq2.20 and eggd_bclconvert

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`TAT_audit/utils/TAT_queries.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/themis/10#-NIIBfoO3E1YIVEWOPEf:-NIIGg9b58DR5-uAWEMj:b4bjnv8) ([raw file](https://github.com/eastgenomics/themis/blob/3165f45d427dcde6c36432c49155469e4345a2a5/TAT_audit/utils/TAT_queries.py#L574)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

other things do get run there / will be (i.e. eggd_conductor), demultiplexing apps will be eggd_bcl2fastq2.20 and eggd_bclconvert
</blockquote></details>

they all seem to have the name BCL to FASTQ v2.20 so changed searching with name :)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`TAT_audit/utils/TAT_queries.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/themis/10#-NIIBfoO3E1YIVEWOPEf:-NIIMrRW2YMz4Old2ff2:bz0e72o) ([raw file](https://github.com/eastgenomics/themis/blob/3165f45d427dcde6c36432c49155469e4345a2a5/TAT_audit/utils/TAT_queries.py#L574)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

they all seem to have the name BCL to FASTQ v2.20 so changed searching with name :)
</blockquote></details>

can you make the searching case insensitive? the bclconvert app is lowercase

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`TAT_audit/utils/TAT_queries.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/themis/10#-NIIBfoO3E1YIVEWOPEf:-NIIQBs62I4ShiwHK3P0:bq79le6) ([raw file](https://github.com/eastgenomics/themis/blob/3165f45d427dcde6c36432c49155469e4345a2a5/TAT_audit/utils/TAT_queries.py#L574)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you make the searching case insensitive? the bclconvert app is lowercase
</blockquote></details>

As far as I can see the actual name of the job only ever seems to be 'BCL to FASTQ v2.2.0', it's the executable name which changes but I have updated anyway

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`TAT_audit/utils/TAT_queries.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/themis/10#-NIIBfoO3E1YIVEWOPEf:-NIISual-pcE_VdjdOSC:b8buq3f) ([raw file](https://github.com/eastgenomics/themis/blob/3165f45d427dcde6c36432c49155469e4345a2a5/TAT_audit/utils/TAT_queries.py#L574)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

As far as I can see the actual name of the job only ever seems to be 'BCL to FASTQ v2.2.0', it's the executable name which changes but I have updated anyway 
</blockquote></details>

 bclconvert app will be coming soon but hasn't been run yet, examples jobs here: https://platform.dnanexus.com/projects/GJxgb004bGXjGVjg4fBky7K6/monitor

will this find those jobs?

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`TAT_audit/utils/TAT_queries.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/themis/10#-NIIBfoO3E1YIVEWOPEf:-NIIUE0p9qwMdTMqElAP:b-75cnaa) ([raw file](https://github.com/eastgenomics/themis/blob/3165f45d427dcde6c36432c49155469e4345a2a5/TAT_audit/utils/TAT_queries.py#L574)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

 bclconvert app will be coming soon but hasn't been run yet, examples jobs here: https://platform.dnanexus.com/projects/GJxgb004bGXjGVjg4fBky7K6/monitor

will this find those jobs?
</blockquote></details>

just checked jobs in that project, yes it finds them :)

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/10#-:-NIIVnku76LLheVyG8Y1:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
